name: CI Workflow
on:
  push:
     branches:
       - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
    - name: Run linter
      run: |
        echo "Running linter..."
        npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Running tests..."
        npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Build application
      run: |
        echo "Building application..."
        npm run build