name: Manual Trigger Workflow
env:
    REPO_URL: ${{ github.repository }}
on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch name to clone'
                required: true
                default: 'main'
                type: choice
                options:
                    - $(git ls-remote --heads $REPO_URL | awk '{print $2}' | sed 's|refs/heads/||')

jobs:
    clone-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Verify branch exists
              run: |
                echo "Checking if branch '${{ github.event.inputs.branch }}' exists..."
                if git ls-remote --heads $REPO_URL ${{ github.event.inputs.branch }} | grep -q ${{ github.event.inputs.branch }}; then
                    echo "Branch '${{ github.event.inputs.branch }}' exists."
                else
                    echo "Branch '${{ github.event.inputs.branch }}' does not exist. Available branches are:"
                    git ls-remote --heads origin | awk '{print $2}' | sed 's|refs/heads/||'
                    exit 1
                fi

            - name: Checkout code
              uses: actions/checkout@v3
              with:
               ref: ${{ github.event.inputs.branch }}
